/// Flutter icons LetsRoll
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LetsRoll
///      fonts:
///       - asset: fonts/LetsRoll.ttf
///
///
///
import 'package:flutter/widgets.dart';

class LetsRoll {
  LetsRoll._();

  static const _kFontFam = 'LetsRoll';
  static const String _kFontPkg = null;

  static const IconData bicycle_rider =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skater =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roller_skate =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
